/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedAddressBookEntriesRouteImport } from './routes/_authenticated.address-book-entries'
import { Route as AuthenticatedDeviceGroupsRouteImport } from './routes/_authenticated.device-groups'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated.tags'
import { Route as AuthenticatedUserGroupsRouteImport } from './routes/_authenticated.user-groups'
import { Route as AuthenticatedAddressBooksIndexRouteImport } from './routes/_authenticated.address-books.index'
import { Route as AuthenticatedAddressBooksCollectionIdRouteImport } from './routes/_authenticated.address-books.$collectionId'
import { Route as AuthenticatedAuditConnectionsRouteImport } from './routes/_authenticated.audit.connections'
import { Route as AuthenticatedAuditFilesRouteImport } from './routes/_authenticated.audit.files'
import { Route as AuthenticatedAuditLoginsRouteImport } from './routes/_authenticated.audit.logins'
import { Route as AuthenticatedAuditSessionsRouteImport } from './routes/_authenticated.audit.sessions'
import { Route as AuthenticatedAuditSharesRouteImport } from './routes/_authenticated.audit.shares'
import { Route as AuthenticatedDevicesIndexRouteImport } from './routes/_authenticated.devices.index'
import { Route as AuthenticatedDevicesNewRouteImport } from './routes/_authenticated.devices.new'
import { Route as AuthenticatedServerCommandsRouteImport } from './routes/_authenticated.server.commands'
import { Route as AuthenticatedServerSettingsRouteImport } from './routes/_authenticated.server.settings'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated.users.index'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated.users.new'
import { Route as AuthenticatedDevicesDeviceIdIndexRouteImport } from './routes/_authenticated.devices.$deviceId.index'
import { Route as AuthenticatedDevicesDeviceIdEditRouteImport } from './routes/_authenticated.devices.$deviceId.edit'
import { Route as AuthenticatedUsersUserIdIndexRouteImport } from './routes/_authenticated.users.$userId.index'
import { Route as AuthenticatedUsersUserIdEditRouteImport } from './routes/_authenticated.users.$userId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddressBookEntriesRoute =
  AuthenticatedAddressBookEntriesRouteImport.update({
    id: '/address-book-entries',
    path: '/address-book-entries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeviceGroupsRoute =
  AuthenticatedDeviceGroupsRouteImport.update({
    id: '/device-groups',
    path: '/device-groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserGroupsRoute = AuthenticatedUserGroupsRouteImport.update({
  id: '/user-groups',
  path: '/user-groups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddressBooksIndexRoute =
  AuthenticatedAddressBooksIndexRouteImport.update({
    id: '/address-books/',
    path: '/address-books/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAddressBooksCollectionIdRoute =
  AuthenticatedAddressBooksCollectionIdRouteImport.update({
    id: '/address-books/$collectionId',
    path: '/address-books/$collectionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditConnectionsRoute =
  AuthenticatedAuditConnectionsRouteImport.update({
    id: '/audit/connections',
    path: '/audit/connections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditFilesRoute = AuthenticatedAuditFilesRouteImport.update({
  id: '/audit/files',
  path: '/audit/files',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLoginsRoute =
  AuthenticatedAuditLoginsRouteImport.update({
    id: '/audit/logins',
    path: '/audit/logins',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditSessionsRoute =
  AuthenticatedAuditSessionsRouteImport.update({
    id: '/audit/sessions',
    path: '/audit/sessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditSharesRoute =
  AuthenticatedAuditSharesRouteImport.update({
    id: '/audit/shares',
    path: '/audit/shares',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevicesIndexRoute =
  AuthenticatedDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevicesNewRoute = AuthenticatedDevicesNewRouteImport.update({
  id: '/devices/new',
  path: '/devices/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServerCommandsRoute =
  AuthenticatedServerCommandsRouteImport.update({
    id: '/server/commands',
    path: '/server/commands',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServerSettingsRoute =
  AuthenticatedServerSettingsRouteImport.update({
    id: '/server/settings',
    path: '/server/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevicesDeviceIdIndexRoute =
  AuthenticatedDevicesDeviceIdIndexRouteImport.update({
    id: '/devices/$deviceId/',
    path: '/devices/$deviceId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevicesDeviceIdEditRoute =
  AuthenticatedDevicesDeviceIdEditRouteImport.update({
    id: '/devices/$deviceId/edit',
    path: '/devices/$deviceId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdIndexRoute =
  AuthenticatedUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/address-book-entries': typeof AuthenticatedAddressBookEntriesRoute
  '/device-groups': typeof AuthenticatedDeviceGroupsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/user-groups': typeof AuthenticatedUserGroupsRoute
  '/address-books/$collectionId': typeof AuthenticatedAddressBooksCollectionIdRoute
  '/audit/connections': typeof AuthenticatedAuditConnectionsRoute
  '/audit/files': typeof AuthenticatedAuditFilesRoute
  '/audit/logins': typeof AuthenticatedAuditLoginsRoute
  '/audit/sessions': typeof AuthenticatedAuditSessionsRoute
  '/audit/shares': typeof AuthenticatedAuditSharesRoute
  '/devices/new': typeof AuthenticatedDevicesNewRoute
  '/server/commands': typeof AuthenticatedServerCommandsRoute
  '/server/settings': typeof AuthenticatedServerSettingsRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/address-books/': typeof AuthenticatedAddressBooksIndexRoute
  '/devices/': typeof AuthenticatedDevicesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/devices/$deviceId/edit': typeof AuthenticatedDevicesDeviceIdEditRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/devices/$deviceId/': typeof AuthenticatedDevicesDeviceIdIndexRoute
  '/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/address-book-entries': typeof AuthenticatedAddressBookEntriesRoute
  '/device-groups': typeof AuthenticatedDeviceGroupsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/user-groups': typeof AuthenticatedUserGroupsRoute
  '/': typeof AuthenticatedIndexRoute
  '/address-books/$collectionId': typeof AuthenticatedAddressBooksCollectionIdRoute
  '/audit/connections': typeof AuthenticatedAuditConnectionsRoute
  '/audit/files': typeof AuthenticatedAuditFilesRoute
  '/audit/logins': typeof AuthenticatedAuditLoginsRoute
  '/audit/sessions': typeof AuthenticatedAuditSessionsRoute
  '/audit/shares': typeof AuthenticatedAuditSharesRoute
  '/devices/new': typeof AuthenticatedDevicesNewRoute
  '/server/commands': typeof AuthenticatedServerCommandsRoute
  '/server/settings': typeof AuthenticatedServerSettingsRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/address-books': typeof AuthenticatedAddressBooksIndexRoute
  '/devices': typeof AuthenticatedDevicesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/devices/$deviceId/edit': typeof AuthenticatedDevicesDeviceIdEditRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/devices/$deviceId': typeof AuthenticatedDevicesDeviceIdIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/address-book-entries': typeof AuthenticatedAddressBookEntriesRoute
  '/_authenticated/device-groups': typeof AuthenticatedDeviceGroupsRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRoute
  '/_authenticated/user-groups': typeof AuthenticatedUserGroupsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/address-books/$collectionId': typeof AuthenticatedAddressBooksCollectionIdRoute
  '/_authenticated/audit/connections': typeof AuthenticatedAuditConnectionsRoute
  '/_authenticated/audit/files': typeof AuthenticatedAuditFilesRoute
  '/_authenticated/audit/logins': typeof AuthenticatedAuditLoginsRoute
  '/_authenticated/audit/sessions': typeof AuthenticatedAuditSessionsRoute
  '/_authenticated/audit/shares': typeof AuthenticatedAuditSharesRoute
  '/_authenticated/devices/new': typeof AuthenticatedDevicesNewRoute
  '/_authenticated/server/commands': typeof AuthenticatedServerCommandsRoute
  '/_authenticated/server/settings': typeof AuthenticatedServerSettingsRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/address-books/': typeof AuthenticatedAddressBooksIndexRoute
  '/_authenticated/devices/': typeof AuthenticatedDevicesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/devices/$deviceId/edit': typeof AuthenticatedDevicesDeviceIdEditRoute
  '/_authenticated/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/_authenticated/devices/$deviceId/': typeof AuthenticatedDevicesDeviceIdIndexRoute
  '/_authenticated/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/address-book-entries'
    | '/device-groups'
    | '/tags'
    | '/user-groups'
    | '/address-books/$collectionId'
    | '/audit/connections'
    | '/audit/files'
    | '/audit/logins'
    | '/audit/sessions'
    | '/audit/shares'
    | '/devices/new'
    | '/server/commands'
    | '/server/settings'
    | '/users/new'
    | '/address-books/'
    | '/devices/'
    | '/users/'
    | '/devices/$deviceId/edit'
    | '/users/$userId/edit'
    | '/devices/$deviceId/'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/address-book-entries'
    | '/device-groups'
    | '/tags'
    | '/user-groups'
    | '/'
    | '/address-books/$collectionId'
    | '/audit/connections'
    | '/audit/files'
    | '/audit/logins'
    | '/audit/sessions'
    | '/audit/shares'
    | '/devices/new'
    | '/server/commands'
    | '/server/settings'
    | '/users/new'
    | '/address-books'
    | '/devices'
    | '/users'
    | '/devices/$deviceId/edit'
    | '/users/$userId/edit'
    | '/devices/$deviceId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/address-book-entries'
    | '/_authenticated/device-groups'
    | '/_authenticated/tags'
    | '/_authenticated/user-groups'
    | '/_authenticated/'
    | '/_authenticated/address-books/$collectionId'
    | '/_authenticated/audit/connections'
    | '/_authenticated/audit/files'
    | '/_authenticated/audit/logins'
    | '/_authenticated/audit/sessions'
    | '/_authenticated/audit/shares'
    | '/_authenticated/devices/new'
    | '/_authenticated/server/commands'
    | '/_authenticated/server/settings'
    | '/_authenticated/users/new'
    | '/_authenticated/address-books/'
    | '/_authenticated/devices/'
    | '/_authenticated/users/'
    | '/_authenticated/devices/$deviceId/edit'
    | '/_authenticated/users/$userId/edit'
    | '/_authenticated/devices/$deviceId/'
    | '/_authenticated/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/address-book-entries': {
      id: '/_authenticated/address-book-entries'
      path: '/address-book-entries'
      fullPath: '/address-book-entries'
      preLoaderRoute: typeof AuthenticatedAddressBookEntriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/device-groups': {
      id: '/_authenticated/device-groups'
      path: '/device-groups'
      fullPath: '/device-groups'
      preLoaderRoute: typeof AuthenticatedDeviceGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user-groups': {
      id: '/_authenticated/user-groups'
      path: '/user-groups'
      fullPath: '/user-groups'
      preLoaderRoute: typeof AuthenticatedUserGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/address-books/': {
      id: '/_authenticated/address-books/'
      path: '/address-books'
      fullPath: '/address-books/'
      preLoaderRoute: typeof AuthenticatedAddressBooksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/address-books/$collectionId': {
      id: '/_authenticated/address-books/$collectionId'
      path: '/address-books/$collectionId'
      fullPath: '/address-books/$collectionId'
      preLoaderRoute: typeof AuthenticatedAddressBooksCollectionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/connections': {
      id: '/_authenticated/audit/connections'
      path: '/audit/connections'
      fullPath: '/audit/connections'
      preLoaderRoute: typeof AuthenticatedAuditConnectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/files': {
      id: '/_authenticated/audit/files'
      path: '/audit/files'
      fullPath: '/audit/files'
      preLoaderRoute: typeof AuthenticatedAuditFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/logins': {
      id: '/_authenticated/audit/logins'
      path: '/audit/logins'
      fullPath: '/audit/logins'
      preLoaderRoute: typeof AuthenticatedAuditLoginsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/sessions': {
      id: '/_authenticated/audit/sessions'
      path: '/audit/sessions'
      fullPath: '/audit/sessions'
      preLoaderRoute: typeof AuthenticatedAuditSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/shares': {
      id: '/_authenticated/audit/shares'
      path: '/audit/shares'
      fullPath: '/audit/shares'
      preLoaderRoute: typeof AuthenticatedAuditSharesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices/': {
      id: '/_authenticated/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthenticatedDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices/new': {
      id: '/_authenticated/devices/new'
      path: '/devices/new'
      fullPath: '/devices/new'
      preLoaderRoute: typeof AuthenticatedDevicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/server/commands': {
      id: '/_authenticated/server/commands'
      path: '/server/commands'
      fullPath: '/server/commands'
      preLoaderRoute: typeof AuthenticatedServerCommandsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/server/settings': {
      id: '/_authenticated/server/settings'
      path: '/server/settings'
      fullPath: '/server/settings'
      preLoaderRoute: typeof AuthenticatedServerSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices/$deviceId/': {
      id: '/_authenticated/devices/$deviceId/'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId/'
      preLoaderRoute: typeof AuthenticatedDevicesDeviceIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices/$deviceId/edit': {
      id: '/_authenticated/devices/$deviceId/edit'
      path: '/devices/$deviceId/edit'
      fullPath: '/devices/$deviceId/edit'
      preLoaderRoute: typeof AuthenticatedDevicesDeviceIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId/': {
      id: '/_authenticated/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof AuthenticatedUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId/edit': {
      id: '/_authenticated/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAddressBookEntriesRoute: typeof AuthenticatedAddressBookEntriesRoute
  AuthenticatedDeviceGroupsRoute: typeof AuthenticatedDeviceGroupsRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
  AuthenticatedUserGroupsRoute: typeof AuthenticatedUserGroupsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAddressBooksCollectionIdRoute: typeof AuthenticatedAddressBooksCollectionIdRoute
  AuthenticatedAuditConnectionsRoute: typeof AuthenticatedAuditConnectionsRoute
  AuthenticatedAuditFilesRoute: typeof AuthenticatedAuditFilesRoute
  AuthenticatedAuditLoginsRoute: typeof AuthenticatedAuditLoginsRoute
  AuthenticatedAuditSessionsRoute: typeof AuthenticatedAuditSessionsRoute
  AuthenticatedAuditSharesRoute: typeof AuthenticatedAuditSharesRoute
  AuthenticatedDevicesNewRoute: typeof AuthenticatedDevicesNewRoute
  AuthenticatedServerCommandsRoute: typeof AuthenticatedServerCommandsRoute
  AuthenticatedServerSettingsRoute: typeof AuthenticatedServerSettingsRoute
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedAddressBooksIndexRoute: typeof AuthenticatedAddressBooksIndexRoute
  AuthenticatedDevicesIndexRoute: typeof AuthenticatedDevicesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedDevicesDeviceIdEditRoute: typeof AuthenticatedDevicesDeviceIdEditRoute
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
  AuthenticatedDevicesDeviceIdIndexRoute: typeof AuthenticatedDevicesDeviceIdIndexRoute
  AuthenticatedUsersUserIdIndexRoute: typeof AuthenticatedUsersUserIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddressBookEntriesRoute: AuthenticatedAddressBookEntriesRoute,
  AuthenticatedDeviceGroupsRoute: AuthenticatedDeviceGroupsRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
  AuthenticatedUserGroupsRoute: AuthenticatedUserGroupsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAddressBooksCollectionIdRoute:
    AuthenticatedAddressBooksCollectionIdRoute,
  AuthenticatedAuditConnectionsRoute: AuthenticatedAuditConnectionsRoute,
  AuthenticatedAuditFilesRoute: AuthenticatedAuditFilesRoute,
  AuthenticatedAuditLoginsRoute: AuthenticatedAuditLoginsRoute,
  AuthenticatedAuditSessionsRoute: AuthenticatedAuditSessionsRoute,
  AuthenticatedAuditSharesRoute: AuthenticatedAuditSharesRoute,
  AuthenticatedDevicesNewRoute: AuthenticatedDevicesNewRoute,
  AuthenticatedServerCommandsRoute: AuthenticatedServerCommandsRoute,
  AuthenticatedServerSettingsRoute: AuthenticatedServerSettingsRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedAddressBooksIndexRoute: AuthenticatedAddressBooksIndexRoute,
  AuthenticatedDevicesIndexRoute: AuthenticatedDevicesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedDevicesDeviceIdEditRoute: AuthenticatedDevicesDeviceIdEditRoute,
  AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
  AuthenticatedDevicesDeviceIdIndexRoute:
    AuthenticatedDevicesDeviceIdIndexRoute,
  AuthenticatedUsersUserIdIndexRoute: AuthenticatedUsersUserIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
